### ISSUE TITLE
Deploy to Bintray snapshots with CircleCI

### ISSUE THREAD

**Issue by tkrille** [osiam/scim-schema#125]

**Comment by dacrome** [comment]
Because the `scim-schema` should be the first one deployed its snapshots with circleci to bintray, I just leaving here the blog posts, which I think are good starting points:
- http://veithen.github.io/2013/05/26/github-bintray-maven-release-plugin.html
- http://www.alexecollins.com/migrating-to-circleci/

**Comment by tkrille** [comment]
scim-schema is obsolete.
